
[functions.generate-story]
enabled = true
verify_jwt = false
import_map = "./functions/generate-story/deno.json"
entrypoint = "./functions/generate-story/index.ts"

[functions.generate-quiz]
enabled = true
verify_jwt = false
entrypoint = "./functions/generate-quiz/index.ts"
